apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jenkinsx
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "799235118493"
    provider: eks
    region: eu-west-2
    registry: 799235118493.dkr.ecr.eu-west-2.amazonaws.com
  environments:
  - key: dev
    owner: debugcarkey
    repository: jx3-eks-cluster
  - key: staging
  - key: production
  ingress:
    domain: 18.134.92.246.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: debugcarkey
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-jenkinsx-20210421162444587500000003
  - name: reports
    url: s3://reports-jenkinsx-20210421162444590100000004
  - name: repository
    url: s3://repository-jenkinsx-20210421162444592700000006
  terraform: true
  vault:
    aws:
      dynamoDBRegion: eu-west-2
      dynamoDBTable: vault-unseal-jenkinsx-bb1IrxTz
      kmsKeyId: ad8906bc-a3a9-4efd-8a2c-1c27f214b5e4
      kmsRegion: eu-west-2
      s3Bucket: vault-unseal-jenkinsx-20210421162446117800000009
      s3Region: eu-west-2
  webhook: lighthouse
